- name : configure cart
  hosts: cart
  become : yes
  tasks:
    - name : disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf: 
          name: nodejs
          state : present

    - name: add cart
      ansible.builtin.user:
         name : roboshop 
         system : true
         home: /app
         shell: /sbin/nologin
         comment : "roboshop system cart" 

    - name : delete directory
      ansible.builtin.file:
        path: /app
        state : absent

    - name: make directory
      ansible.builtin.file:
         name: /app
         state: directory

    - name : delete directory
      ansible.builtin.file:
        path: /tmp/cart.zip
        state : absent

    - name: download the code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest : /tmp/cart.zip

    - name : unzip the file
      ansible.builtin.unarchive:
        src : /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: npm install
      community.general.npm:
        path : /app

    - name : copy the cart service
      ansible.builtin.copy:
        src : cart.service
        dest : /etc/systemd/system

    - name: deamon reload
      ansible.builtin.systemd:
        name : cart
        daemon_reload: yes

    - name: enable and restart the cart
      ansible.builtin.service:
         name : cart
         state : started
         enabled: yes


         