- name : configure catalouge
  hosts: catalogue
  become: yes
  tasks :
    - name : enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name : install nodejs
      ansible.builtin.dnf:
       name : nodejs
       state : present

    - name : useradd
      ansible.builtin.user:
       name : roboshop 
       system : true
       home : /app
       shell : /sbin/nologin
       comment : "roboshop system user"

    - name : make directory
      ansible.builtin.file: 
        path: /app
        state: directory

    - name : download the code
      ansible.builtin.get_url:
        url : https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name : unzip the file
      ansible.builtin.unarchive:
        src : /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name : download dependencies
      community.general.npm:
        path: /app
        
    - name : copy the catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: copy mongo repo
      ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

    - name : install mongodb client
      ansible.builtin.dnf:
        name : mongodb-mongosh
        state: present

    - name: check the products loaded or not
      ansible.builtin.command: mongosh --host "{{mongodb_host}}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: pront the catalouge_output
      ansible.builtin.debug:
        msg: "{{catalogue_output}}"

    - name : load the products
      ansible.builtin.command: mongosh --host MONGODB-SERVER-IPADDRESS </app/db/master-data.js
      when: catalogue_output.stdout | int < 0

  
