- name : configure rabbitmq
  hosts: rabbitmq
  become: yes
  tasks: 
    - name: copy the rabbitmq repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq
      ansible.builtin.dnf:
        name : rabbitmq-server
        state : present

    - name: enable and start rabbitmq
      ansible.builtin.service:
        state : restarted
        enabled : yes

    - name: useradd in rabbitmq
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: "roboshop123" # Consider using Ansible Vault for sensitive data
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present

    - name : give permission
      ansible.builtin.file:
      path: /opt/app/config.ini
        owner: root
        group: webapp
        mode: '0644'