- name : roboshop
  hosts: all
  connection : local
  vars: 
   sg_id: "sgr-0e99394019f292c77"
   ami_id: "ami-0220d79f3f480ecf5"
   instances :
     - Mongodb
     - catalouge
   env: dev
  tasks: 
    - name : create instances
      amazon.aws.ec2_instance:
        instance_type : "t3.micro"
        security_group: "{{ sg_id }}" 
        image_id: "{{ ami_id }}"
        name : "{{item}} - {{ env }}" 
        tags: 
          Name : "{{item}} - {{ env }}"
          Project : roboshop
          Environment : "{{env}}"
      loop : "{{instances}}"
      register : ec2_output

    - name : print the ec2_output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"
     
