- name : roboshop
  hosts: all
  connection : local
  vars: 
   sg_id: "sg-0b4c1bffcd0783883"
   ami_id: "ami-0220d79f3f480ecf5"
   instances :
     - Mongodb
     - catalouge
   env: dev
   domainname: "devopswithsai.online"
  tasks: 
    - name : create instances
      amazon.aws.ec2_instance:
        instance_type : "t3.micro"
        security_group: "{{ sg_id }}" 
        image_id: "{{ ami_id }}"
        name : "{{item}} - {{ env }}" 
        tags: 
          Name : "{{item}} - {{ env }}"
          Project : roboshop
          Environment : "{{env}}"
      loop : "{{instances}}"
      register : ec2_output

    - name : print the ec2_output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"

    - name: create route 53 records
      amazon.aws.route53:
        state : present
        zone: "{{domainname}}"
        record: "{{item.item}}-{{env}}.{{domainname}}"
        type: A 
        ttl : 1
        value: "{{item.instances[0].private_ip_address}}"
        wait: true
      loop: "{{ec2_output.results}}"
     
