#ansible-playbook -i localhost, -e '{"instances":["mongodb","catalogue","cart","redis","mysql","rabbitmq","user","shipping","payment","frontend"]}' roboshop.yaml
- name : roboshop
  hosts: all
  connection : local
  vars: 
   sg_id: "sg-0b4c1bffcd0783883"
   ami_id: "ami-0220d79f3f480ecf5"
   instances :
     - Mongodb
     - catalouge
   env: dev
   action : create
   domainname: "devopswithsai.online"
  tasks: 

    - name : create instances
      amazon.aws.ec2_instance:
        instance_type : "t3.micro"
        security_group: "{{ sg_id }}" 
        image_id: "{{ ami_id }}"
        name : "{{item}} - {{ env }}" 
        tags: 
          Name : "{{item}} - {{ env }}"
          Project : roboshop
          Environment : "{{env}}"
      loop : "{{instances}}"
      register : ec2_output
      when : action == create
    - name : print the ec2_output
      ansible.builtin.debug:
        msg: "{{ec2_output}}"
      when : action == "create"
       

    - name: create route 53 records
      amazon.aws.route53:
        state : present
        zone: "{{domainname}}"
        record: "{{item.item}}-{{env}}.{{domainname}}"
        type: A 
        ttl : 1
        value: "{{item.instances[0].private_ip_address}}"
        wait: false
        overwrite: true
      loop: "{{ec2_output.results}}"
      when : action == "create"

    - name: create route 53 records
      amazon.aws.route53:
        state : present
        zone: "{{domainname}}"
        record: "Roboshop-{{env}}.{{domainname}}"
        type: A 
        ttl : 1
        value: "{{item.instances[0].public_ip_address}}"
        wait: false
      loop: "{{ec2_output.results}}"
      when :
       - action == create
       - item.item == frontend

    - name : delete ec2_instance
      amazon.aws.ec2_instance:
        state : absent
        name : "{{item}}-{{env}}"
        wait: false
      loop: "{{instances}}"
      when: action == "destroy"
      